version: 2.1

parameters:
  node-version:
    type: string
    default: '20.17.0'

  cypress-version:
    type: string
    default: '13.11.0'

commands:
  yarn-install:
    steps:
      - run: date +"%Y-%m" > /tmp/month.txt && cat /tmp/month.txt
      - restore_cache:
          keys:
            - yarn-{{ .Environment.YARN_CACHE_VERSION }}-{{ checksum "/tmp/month.txt" }}-{{ checksum "yarn.lock" }}
            - yarn-{{ .Environment.YARN_CACHE_VERSION }}-{{ checksum "/tmp/month.txt" }}-
      - run:
          name: 'corepack enable'
          command: |-
            if command -v sudo; then
              sudo corepack enable
            else
              corepack enable
            fi
      - run: corepack install
      - run: yarn -v
      - run: yarn install --immutable
      - save_cache:
          key: yarn-{{ .Environment.YARN_CACHE_VERSION }}-{{ checksum "/tmp/month.txt" }}-{{ checksum "yarn.lock" }}
          paths:
            - '~/.yarn/berry'

jobs:
  checks:
    working_directory: /tmp/app
    docker:
      - image: cimg/node:<< pipeline.parameters.node-version >>
    steps:
      - checkout
      - yarn-install
      - run: yarn npm audit
      - run: yarn dedupe --check
      - run: yarn deps
      - run: yarn deps:mismatched
      - run: yarn deps:circular
      - run: yarn pretty
      - run: yarn lint
      - run: yarn svg:check

  tests:
    working_directory: /tmp/app
    docker:
      - image: cimg/node:<< pipeline.parameters.node-version >>
    steps:
      - checkout
      - yarn-install
      - run: NODE_ENV=test yarn test --coverage --coverageReporters=json --reporters=jest-junit --runInBand
      - store_test_results:
          path: './junit.xml'
      - store_artifacts:
          path: 'coverage'

  typecheck:
    working_directory: /tmp/app
    docker:
      - image: cimg/node:<< pipeline.parameters.node-version >>
    steps:
      - checkout
      - yarn-install
      - run: yarn codegen
      - run: yarn build:ts
      - run: git diff --name-only --exit-code
      - run: yarn typecheck

workflows:
  ui:
    unless:
      or:
        - equal: ['skip-tests', << pipeline.git.branch >>]

    jobs:
      - checks
      - typecheck
      - tests
